<!--<div class="header mb-4 h-32 align-middle flex items-center justify-center bg-blue-500">
    <h1 class="text-2xl font-bold text-white text-center">TO-DO</h1>
</div>-->
<div class="taskContainer p-4 bg-gray-300 max-w-4xl self-center rounded-xl shadow-lg ">    
    <h3 class="flex justify-center font-bold">Editar tarea</h3>
   
    <?php if ($this->task): ?>
        <form action="<?php echo WEB_ROOT; ?>/task/updateTask" method="POST">
            <div class="taskItem p-4 pb-0 mb-4  display: grid grid-cols-5 gap-4">
                <div class="flex justify-center">Nombre</div>
                <div class="flex justify-center">Descripción</div>
                <div class="flex justify-center">Categoria</div>
                <div class="flex justify-center">Estado</div>
                <div class="flex justify-end pr-6">Botones</div>
            </div>
            <div class="taskItem border p-4 mb-4 bg-white rounded-xl shadow display: grid grid-cols-5 gap-4 h-60">
                <input type="hidden" name="id_task" value="<?= $this->task['id_task']; ?>">
                <input class="bg-gray-200 pl-2 rounded" type="text" name="name" value="<?= htmlspecialchars($this->task['name']); ?>" maxlength="20">
                <textarea class="bg-gray-200 pl-2 rounded resize-none text-justify align-middle" type="text" name="description" maxlength="100"><?= htmlspecialchars($this->task['description']); ?></textarea>
                
                <select name="category_id">
                    <?php foreach ($this->categories as $cat): ?>
                        <option value="<?= $cat['id'] ?>"
                            <?= $cat['id'] == $this->task['category_id'] ? 'selected' : '' ?>>
                            <?= ucfirst(str_replace('_', ' ', $cat['name'])) ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                
                <select name="state">
                    <?php foreach ($this->states as $state): ?>
                        <option value="<?= $state->name ?>"
                            <?= $state->name == $this->task['state'] ? 'selected' : '' ?>>
                            <?= ucfirst(str_replace('_', ' ', $state->name)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <div class="flex justify-end">
                    <button type="submit" class="py-2 px-4 rounded">
                        <img src="<?= WEB_ROOT ?>/images/salvar.png" alt="Guardar" class="w-4 h-4"></img>
                    </button>
                    <button type="cancel" class="py-2 px-4 rounded" onclick="javascript:window.location='<?php echo WEB_ROOT; ?>/task';">
                        <img src="<?= WEB_ROOT ?>/images/cerrar.png" alt="Cancelar" class="w-4 h-4"></img>
                    </button>
                   
                </div>
            </div>
        </form>
    <?php else: ?>
        <p class="text-red-600">Error: tarea no encontrada</p>
        <div class="flex justify-end">
            <button type="cancel" class="py-2 px-4 rounded" onclick="javascript:window.location='<?php echo WEB_ROOT; ?>/task';">
                <img src="<?= WEB_ROOT ?>/images/cerrar.png" alt="Cancelar" class="w-4 h-4"></img>
            </button>
        </div>
    <?php endif; ?>
</div>    

