<div class="addTaskContainer mb-4 p-4 ml-6 mt-8 bg-green-700 max-w-4xl self-center rounded-xl shadow-lg"> 
    <h2 class="text-xl font-bold mb-2">Hoy</h2>
    <p><?php 
        $fecha = new DateTime();
        $date = date('l, j F'); echo $date; 
    ?></p>
    <h3 class="text-xl font-bold mb-2">Agregar nueva tarea</h2>
    
    <form action=<?= WEB_ROOT ?>/task/addTask method="POST" class="flex flex-col gap-4">
        <input type="text" name="name" placeholder="Nombre de la tarea" required class="p-2 rounded border border-gray-300" maxlength="20">
        <textarea name="description" placeholder="Descripción de la tarea" required class="p-2 rounded border border-gray-300" maxlength="100"></textarea>
        <select name="category_id" required>
            <option value="" disabled selected>Selecciona la categoría</option>
            <?php foreach ($this->categories as $category): ?>
                <option value="<?= $category['id'] ?>">
                    <?= htmlspecialchars($category['name']) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <input type="date" required name="start_date" value="<?php echo date('Y-m-d'); ?>" />
        <button type="submit" class="bg-white hover:bg-gray-200 text-black font-bold py-2 px-4 rounded">Agregar tarea</button>
    </form>
</div>
<div class="taskContainer p-4 ml-6 bg-gray-300 max-w-4xl self-center rounded-xl shadow-lg ">
    <?php 
    $displayTasks = $this->view->tasks ?? $this->tasks ?? [];
    
    if (empty($displayTasks)): 
        echo "<p>No hay tareas disponibles.</p>";
    else:
        foreach ($displayTasks as $task): ?>
            <div class="taskItem border p-4 mb-4 bg-white rounded-xl shadow display: grid grid-cols-6 gap-4">
                
                <div class="flex justify-center items-center">
                    <input <?= $task['state'] === 'completed' ? 'checked' : '' ?> id="green-checkbox" type="checkbox" class="w-4 h-4 bg-green-500 border-default-medium rounded-xs" onclick="return false;">
                </div>
                <div class="text-xl font-bold <?= $task['state'] === 'completed' ? 'line-through' : '' ?>"><?php echo htmlspecialchars($task['name']); ?></div>
                <p class="text-sm text-gray-500"><?php echo htmlspecialchars($task['state']);  ?></p>
                <p class="text-sm text-gray-800"><?php echo htmlspecialchars($task['creation_date']); ?></p>
                <p class="text-sm text-gray-500"><?php echo htmlspecialchars($this->categoriesById[$task['category_id']]);  ?></p>
                <div class="flex justify-end">
                    <?php 
                    $taskId = isset($task['id_task']) ? $task['id_task'] : ''; 
                    $urlEdit = WEB_ROOT . "/task/editTask?id_task=" . $taskId;
                    ?>
                    <a href="<?php echo $urlEdit; ?>">                       
                        <button type="button" class="py-2 px-4 rounded"><img src="<?= WEB_ROOT ?>/images/lapiz.png" alt="Editar" class="w-4 h-4"></img></button>
                    </a>
                
                    <?php 
                    $taskId = isset($task['id_task']) ? $task['id_task'] : ''; 
                    $urlDelete = WEB_ROOT . "/task/deleteTask?id_task=" . $taskId;
                    ?>
                    <a href="<?php echo $urlDelete; ?>" onclick="return confirm('Confirm delete task');">
                        <button type="button" class="py-2 px-4 rounded"><img src="<?= WEB_ROOT ?>/images/papelera.png" alt="Eliminar" class="w-4 h-4"></img></button>
                    </a>
                </div>

            </div>
            <?php endforeach; ?>
    <?php endif; ?>
    </div>
