<?php if (isset($_SESSION['info_message'])): ?>
    <div class="bg-red-500 text-white p-3">
        <?= $_SESSION['info_message']; unset($_SESSION['info_message']); ?>
    </div>
<?php endif; ?>

<?php include __DIR__ . '/../header/header.phtml'; ?>

<div class="pl-12 pb-1 pt-2 mb-4 bg-teal-800 self-center"> 
    <!--
    Cabecera
    -->
    <h1 class="text-4xl font-bold mb-2 text-white">Hoy</h1>
    <p class="text-white text-xl"><?php 
        $fecha = new DateTime();
        $formatter = new IntlDateFormatter(
            'es_ES',
            IntlDateFormatter::FULL,
            IntlDateFormatter::NONE,
            null,
            null,
            "EEEE, d 'de' MMMM"
        );
        echo ucfirst($formatter->format($fecha));
        ?></p>
    
    <div class="flex justify-end mr-6 -mt-9 pb-4"> <?php $urlAdd = WEB_ROOT . "/task/addTask"; ?>
        <a href="<?= $urlAdd ?>" class="inline-flex items-center gap-2 bg-teal-700 
            hover:bg-teal-400 text-white font-medium py-2 px-3 rounded-2xl shadow-lg">
            + Añadir tarea
        </a>
    </div>
</div>

<div class="m-6">
    <hr>
</div>
 
<!-- FILTRO -->
    <div class="filtersContainer ml-6 py-2 pl-2 border rounded-2xl shadow-lg bg-white">
        <!-- <form action="<?= WEB_ROOT ?>/task/filter" method="GET" style="display: flex; gap: 10px; align-items: center;" >-->
        <form action="<?= WEB_ROOT ?>/task/filter" method="GET" class="flex gap-2 align-center">
            
            <input type="text" name="search" class="rounded-xl pl-2 bg-gray-100 text-gray-500" placeholder="Buscar por nombre..." 
                value="<?= $_GET['search'] ?? '' ?>">

            <?php if ($_SESSION['type'] === 'Admin'): ?>
                <select name="user_id" class="bg-gray-100 text-gray-500 rounded-xl shadow-lg py-1 px-2">
                    <option value="">Usuario</option>
                    <?php foreach ($this->users as $user): ?>
                        <option value="<?= $user['id'] ?>" <?= (isset($_GET['user_id']) && $_GET['user_id'] == $user['id']) ? 'selected' : '' ?>>
                            <?= $user['nickname'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>

            <select name="category_id" class="bg-gray-100 text-gray-500 rounded-xl shadow-lg py-1 px-2">
                <option value="">Categoría</option>
                <?php foreach ($this->categories as $category): ?>
                    <option value="<?= $category['id'] ?>" <?= (isset($_GET['category_id']) && $_GET['category_id'] == $category['id']) ? 'selected' : '' ?>>
                        <?= $category['name'] ?>
                    </option>
                <?php endforeach; ?>
            </select>

            <select name="state" class="bg-gray-100 text-gray-500 rounded-xl shadow-lg py-1 px-2">
                <option value="">Estado</option>
                <option value="pending" <?= (isset($_GET['state']) && $_GET['state'] == 'pending') ? 'selected' : '' ?>>Pendiente</option>
                <option value="inProgress" <?= (isset($_GET['state']) && $_GET['state'] == 'inProgress') ? 'selected' : '' ?>>En progreso</option>
                <option value="completed" <?= (isset($_GET['state']) && $_GET['state'] == 'completed') ? 'selected' : '' ?>>Completada</option>
            </select>

            <button type="submit" class="py-2 px-4 rounded-xl bg-teal-800 text-white hover:bg-teal-900 transition">Filtrar</button>
            <a href="<?= WEB_ROOT ?>/task" class="py-2 px-4 rounded-xl bg-teal-800 text-white hover:bg-teal-900 transition">Limpiar</a>
        </form>
    </div>
    <!-- HASTA AQUI CODIGO NUEVO DE FILTRO -->

<div class="m-6">
    <hr>
</div>
<div class="taskContainer p-4 pl-0 ml-6 mr-6 w-full self-center grid gap-x-4 gap-y-8 justify-center items-stretch [grid-template-columns:repeat(auto-fit,minmax(300px,1fr))]">
    <?php 
    $displayTasks = $this->tasks ?? [];
    
    if (empty($displayTasks)): 
        echo "<p>No hay tareas disponibles.</p>";
    else:
        foreach ($displayTasks as $task): ?>
        <div class="p-4 mb-4 bg-white rounded-3xl shadow-lg grid gap-2 h-full max-w-[300px] w-full">
            <div class="grid grid-cols-2 gap-8"> <!--1 estado y categoria-->
                
                <div class="rounded-2xl shadow-lg text-white flex justify-center h-8 text-sm items-center
                    <?= $task['state'] === 'completed' ? 'bg-teal-700' : '' ?>
                    <?= $task['state'] === 'inProgress' ? 'bg-teal-400' : '' ?>
                    <?= $task['state'] === 'pending' ? 'bg-gray-400' : '' ?>
                ">
                    <?php echo $task['state'] ?>
                </div>
                <div class="shadow-lg text-white text-sm flex justify-center h-8 bg-<?= $this->categoriesColorById[$task['category_id']] ?>-600">
                    <p class="flex justify-end items-center"><?php echo htmlspecialchars($this->categoriesById[$task['category_id']]); ?></p>
                </div>
            </div>
            <div><!--2 nombre tarea -->
                <p class="text-black-500 font-bold text-2xl break-keep"><?php echo htmlspecialchars($task['name']); ?></p>
            </div>
            <div><!--3 descripcion tarea -->
                <p class="text-sm text-gray-500 col-span-4 break-all h-20"><?php echo htmlspecialchars($task['description']);  ?></p>
            </div>
            <div><!--4 fecha inicio -->
                <p class="text-sm text-gray-800"><?php echo htmlspecialchars($task['start_date']); ?></p>
            </div>
            <div><!--5 hora inicio y final -->
                <p class="text-sm text-gray-800"><?php echo $task['start_time'] . " - " . $task['end_time'] ?></p>
            </div>
            <div class="mt-auto"><!--6 botones -->
                <div class="flex justify-end">
                    <?php 
                        $taskId = isset($task['id_task']) ? $task['id_task'] : ''; 
                        $urlEdit = WEB_ROOT . "/task/editTask?id_task=" . $taskId;
                    ?>
                    <a href="<?php echo $urlEdit; ?>">                       
                        <button type="button" class="py-2 px-4 rounded"><img src="<?= WEB_ROOT ?>/images/lapiz.png" alt="Editar" class="w-4 h-4"></img></button>
                    </a>                
                    <?php 
                        $taskId = isset($task['id_task']) ? $task['id_task'] : ''; 
                        $urlDelete = WEB_ROOT . "/task/deleteTask?id_task=" . $taskId;
                    ?>
                    <a href="<?php echo $urlDelete; ?>" onclick="return confirm('¿Estas seguro que quieres eliminar esta tarea?');">
                        <button type="button" class="py-2 px-4 rounded"><img src="<?= WEB_ROOT ?>/images/papelera.png" alt="Eliminar" class="w-4 h-4"></img></button>
                    </a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
