<h1>User Management System</h1>

<div style="background: #f4f4f4; padding: 15px; border: 1px solid #ccc; margin-bottom: 20px;">
    <h3>Edit User</h3>
    <form action="<?php echo WEB_ROOT; ?>/user/update" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>">
        <input type="text" name="nickname" value= <?php echo $this->user['nickname']; ?>>
        <input type="text" name="name" value= <?php echo $this->user['name']; ?>>
        <input type="text" name="surname" value= <?php echo $this->user['surname']; ?>>
        <input type="email" name="email" value= <?php echo $this->user['email']; ?>>
        <input type="password" name="password" value= <?php echo $this->user['password']; ?>>
        <select name="type">
            <option value="Guest">Guest</option>
            <option value="Admin">Admin</option>
        </select>
        <button type="submit">Save Changes</button>
        <a href="<?php echo WEB_ROOT; ?>/user">Cancel</a>
    </form>
</div>
