<?php include __DIR__ . '/../header/header.phtml'; ?>

<div class="p-4 max-w-2xl absolute top-16 left-1/2 -translate-x-1/2 w-full">
    
    <form action="<?php echo WEB_ROOT; ?>/user/update" method="POST">
        
        <div class="min-w-2xl border p-6 pb-8 mb-4 bg-white rounded-3xl shadow-lg grid gap-4">
            
            <div>
                <div class="text-black-500 font-bold text-3xl">Editar usuario</div>
                <div class="text-black-500 text-xl">Modifica los datos del perfil seleccionado</div>
            </div>

            <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>">

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Nickname</label>
                    <input class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none focus:ring-2 focus:ring-teal-500" 
                           required type="text" name="nickname" value="<?php echo $this->user['nickname']; ?>">
                </div>
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Email</label>
                    <input class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none focus:ring-2 focus:ring-teal-500" 
                           required type="email" name="email" value="<?php echo $this->user['email']; ?>">
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Nombre</label>
                    <input class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none" 
                           required type="text" name="name" value="<?php echo $this->user['name']; ?>">
                </div>
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Apellido</label>
                    <input class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none" 
                           required type="text" name="surname" value="<?php echo $this->user['surname']; ?>">
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Contraseña</label>
                    <input class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none" 
                           required type="password" name="password" value="<?php echo $this->user['password']; ?>">
                </div>
                <div class="flex flex-col gap-1">
                    <label class="text-black-500 font-bold text-base">Tipo de usuario</label>
                    <select name="type" class="bg-gray-100 text-gray-700 pl-3 rounded-xl shadow-md py-2 border-none appearance-none cursor-pointer">
                        <option value="Member" <?php echo ($this->user['type'] == 'Member') ? 'selected' : ''; ?>>Member</option>
                        <option value="Admin" <?php echo ($this->user['type'] == 'Admin') ? 'selected' : ''; ?>>Admin</option>
                    </select>
                </div>
            </div>

            <hr class="my-2">

            <div class="flex justify-end gap-4">
                <div class="flex justify-center">
                    <a href="<?php echo WEB_ROOT; ?>/userAdmin" class="py-2 px-6 rounded-xl border 
                    border-teal-800 text-teal-800 hover:bg-gray-100 transition-colors shadow-lg">
                        Cancelar
                    </a>
                </div>

                <div class="flex justify-center">
                    <button type="submit" class="py-2 px-6 rounded-xl border bg-teal-800 text-white shadow-lg">
                        Aceptar
                    </button>
                </div>
            </div>

        </div>
    </form>
</div>