<?php include __DIR__ . '/../header/header.phtml'; ?>


<div class="pl-6 pb-4 pt-10 mb-4 bg-teal-800 self-center h-40">

</div>


<div class="p-4 max-w-xl absolute top-16 left-1/2 -translate-x-1/2 w-full">
    <form method="POST" action="<?= WEB_ROOT ?>/category/add">


        <div class="min-w-3xl taskItem border p-6 pb-8 mb-4 bg-white rounded-3xl shadow-lg grid gap-4">

            <div class="text-black-500 font-bold text-3xl">Añadir Categoría</div>
            <div class="text-black-500 text-m">Define una categoría donde englobar tus tareas</div>

            <div class="w-full">

                <div class="text-black-500 font-bold text-base py-2 ">Nombre</div>
                <input type="text" name="name"
                    class="bg-gray-100 text-gray-500 pl-2 rounded-xl shadow-lg py-2 w-full border p-6"
                    required>


                <div class="text-black-500 font-bold text-base py-2">Descripción</div>
                <textarea name="description"
                    class="bg-gray-100 text-gray-500 pl-2 rounded-xl shadow-lg py-2 w-full h-32 resize-none border p-6"
                    required></textarea>

                <div class="text-black-500 font-bold text-base py-2">Color</div>

                <div class="flex gap-4 justify-center">

                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="red-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-red-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>


                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="emerald-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-emerald-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>


                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="blue-500" class="hidden peer">

                        <div class="w-8 h-8 rounded-full bg-blue-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>


                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="indigo-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-indigo-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

    
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="violet-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-violet-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

      
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="slate-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-slate-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

       
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="amber-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-amber-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

      
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="cyan-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-cyan-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

            
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="stone-700" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-stone-700
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>

               
                    <label class="cursor-pointer">
                        <input type="radio" name="color" value="teal-500" class="hidden peer">
                        <div class="w-8 h-8 rounded-full bg-teal-500
                                    opacity-40
                                    transition-all duration-200
                                    peer-checked:opacity-100
                                    peer-checked:scale-110">
                        </div>
                    </label>
                </div>
            </div>

       
            <hr class="border-t border-gray-300 my-4">

         
            <div class="flex justify-end gap-4">

           
                <a href="<?= WEB_ROOT ?>/category"
                    class="py-2 px-6 rounded-xl border border-teal-800 text-teal-800 hover:bg-gray-100 transition-colors shadow-lg">
                    Cancelar
                </a>
      
                <button type="submit" class="py-2 px-6 rounded-xl border bg-teal-800 text-white shadow-lg">
                    Aceptar
                </button>
            </div>

        </div>

    </form>
</div>