<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <title>TODO App</title>
    
    <!-- Configurar SOLO tus colores personalizados -->
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'verde': '#177062',      
                        'gris': '#AEAEAE',    
                        'gris-oscuro': '#727272', 
                    }
                }
            }
        }
    </script>
</head>
<body class="bg-gray-100">
    <?php echo $this->content(); ?>
</body>
</html>